version: "3.9"

services:

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


  cassandra-seed:
    image: cassandra
    container_name: cassandra1
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=Stellar-cluster
      - CASSANDRA_SEEDS=cassandra-seed
    networks:
      - cassandra-network
    volumes:
      - cassandra-seed-data:/var/lib/cassandra


  cassandra2:
    image: cassandra
    container_name: cassandra2
    ports:
      - 9043:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=Stellar-cluster
      - CASSANDRA_SEEDS=cassandra-seed
    networks:
      - cassandra-network
    volumes:
      - cassandra2-data:/var/lib/cassandra
 
  cassandra3:
    image: cassandra
    container_name: cassandra3
    ports:
      - 9044:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=Stellar-cluster
      - CASSANDRA_SEEDS=cassandra-seed
    networks:
      - cassandra-network
    volumes:
      - cassandra3-data:/var/lib/cassandra

networks:
  cassandra-network:
    driver: bridge

volumes:
  cassandra-seed-data:
  cassandra2-data:
  cassandra3-data: