version: "3.9"

services:
  cassandra:
    image: cassandra
    volumes:
      - ./mnt/cassandra:/var/lib/cassandra
    ports:
      - 9042:9042
  
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


  
  